version: '3.7'

services:
  db:
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  nodejs:
    build: ./gate-simulator
    ports:
      - "9999:9999"